import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/Sidebar";
import Topbar from "./component/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased flex gap-6 w-full`}
      >
        <div className="mx-6 my-8 ">
          <Sidebar />
        </div>
        <div className="w-full mr-12">
          <div className="mt-[26px] mb-[43px]">
            <Topbar />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
