import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./component/Sidebar";
import Topbar from "./component/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Delivary App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" w-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased md:flex gap-6 w-full relative`}
      >
        <div className="md:mx-6 md:mb-8">
          <Sidebar />
        </div>
        <div className="w-full md:mr-12 ml-0 md:ml-24">
          <div className="md:mt-[26px] mb-[43px]">
            <Topbar />
          </div>
          <div className="mt-28 md:mt-0 mx-2 md:mx-0">{children}</div>
        </div>
      </body>
    </html>
  );
}
